theme: minima

title: Samyak Jain
description: >
  Exploring Artificial Intelligence, Machine Learning, Data Science,
  and Open Source — one project at a time.

author: Samyak Jain

show_excerpts: true
